function handleTasksFile(file){if(!file)return;var r=new FileReader();r.onload=function(e){try{var wb=XLSX.read(e.target.result,{type:'array',cellDates:true,dateNF:'yyyy.mm.dd'});var ws=wb.Sheets[wb.SheetNames[0]];var raw=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true});if(raw.length<3){toast('Короткий файл');return;}var hRow=0;for(var i=0;i<Math.min(raw.length,10);i++){for(var j=0;j<raw[i].length;j++){if(String(raw[i][j]).trim()==='Тема'){hRow=i;break;}}}S.headers=[];for(var j=0;j<raw[hRow].length;j++)S.headers.push(String(raw[hRow][j]).trim()||'Col_'+j);S.tasks=[];S.colWidths={};for(var i=hRow+1;i<raw.length;i++){var row=raw[i];if(!row||row.every(function(c){return String(c).trim()==='';}))continue;var obj={};S.headers.forEach(function(h,idx){obj[h]=row[idx]!==undefined?row[idx]:'';});S.tasks.push(obj);}var prio={'Тема':1,'Тип':1,'Основание':1,'Сектор (группа)':1,'Задача исполнителя':1,'Контр. Срок':1,'Фамилия И.О.':1,'Статус':1,'Начало':1,'Окончание':1,'План':1,'Факт':1,'Подтверждающий документ':1};S.visCols={};S.headers.forEach(function(h){S.visCols[h]=!!prio[h];});S.filters={};S.search='';S.groupBy='';S.sortCol='';S.sortDir=1;S.assignments={};$('fileInfo').textContent=file.name+' — '+S.tasks.length+' записей';initApp();toast('Загружено: '+S.tasks.length);}catch(err){toast('Ошибка: '+err.message);}};r.readAsArrayBuffer(file);}

function handleExecFile(file){if(!file)return;var r=new FileReader();r.onload=function(e){try{var text=e.target.result;var lines=text.split(/\r?\n/).filter(function(l){return l.trim();});if(lines.length<2){toast('Пусто');return;}var delim=lines[0].indexOf(';')>-1?';':lines[0].indexOf('\t')>-1?'\t':',';var hdrs=lines[0].split(delim).map(function(h){return h.trim();});S.executors=[];for(var i=1;i<lines.length;i++){var vals=lines[i].split(delim).map(function(v){return v.trim();});var obj={};hdrs.forEach(function(h,j){obj[h]=vals[j]||'';});if(obj['ФИО'])S.executors.push(obj);}$('execCount').textContent='('+S.executors.length+')';if(S.tasks.length>0){buildFilters();render();}toast('Исполнителей: '+S.executors.length);}catch(err){toast('Ошибка: '+err.message);}};r.readAsText(file,'utf-8');}

function initApp(){$('emptyState').classList.add('hidden');$('mainApp').classList.remove('hidden');buildGrp();buildFilters();buildColPanel();renderSaved();render();}
function renderStats(){var t=S.tasks.length,c={};S.tasks.forEach(function(r){var s=String(r['Статус']||'').trim();if(s)c[s]=(c[s]||0)+1;});var items=[{l:'Всего',v:t,c:'c0',i:'fa-list-check'},{l:'Сорвана',v:c['Сорвана']||0,c:'c1',i:'fa-circle-xmark'},{l:'Уточнена',v:c['Уточнена']||0,c:'c2',i:'fa-pen'},{l:'Перенесена',v:c['Перенесена']||0,c:'c3',i:'fa-arrow-right'},{l:'Выполняется',v:c['Выполняется']||0,c:'c4',i:'fa-spinner'},{l:'Назначено',v:Object.keys(S.assignments).length,c:'c5',i:'fa-user-check'}];$('statsBar').innerHTML=items.map(function(x){return '<div class="sc '+x.c+'"><div class="flex items-center justify-between"><span class="text-[10px] text-[var(--mt)] uppercase tracking-wide font-semibold">'+x.l+'</span><i class="fa-solid '+x.i+' text-[10px] text-[var(--mt)] opacity-40"></i></div><div class="text-xl font-bold mono mt-1">'+x.v+'</div></div>';}).join('');}
function uniq(c){var s={};S.tasks.forEach(function(t){var v=String(t[c]||'').trim();if(v)s[v]=1;});return Object.keys(s).sort(function(a,b){return a.localeCompare(b,'ru');});}
function safeId(s){return s.replace(/[^a-zA-Zа-яА-Я0-9]/g,'_');}
function buildFilters(){var p=$('fPanel'),fC=S.headers.filter(function(h){return uniq(h).length>1&&uniq(h).length<80;});p.innerHTML=fC.map(function(c){var v=uniq(c),a=S.filters[c]||{},n=0;for(var k in a)if(a[k])n++;var h=n>0,l=c.length>16?c.slice(0,14)+'…':c;return '<div class="relative"><button class="fb '+(h?'on':'')+'" onclick="toggleDD(this,\'f_'+safeId(c)+'\')">'+esc(l)+(h?' ('+n+')':'')+' <i class="fa-solid fa-chevron-down text-[8px]"></i></button><div class="fd" id="f_'+safeId(c)+'"><div style="padding:3px 7px 5px;border-bottom:1px solid var(--bd);margin-bottom:4px"><button class="text-[10px] text-[var(--mt)] font-semibold" style="background:none;border:none;cursor:pointer" onclick="filterAll(\''+escA(c)+'\',true)">Все</button><span class="text-[10px] text-[var(--bd)] mx-1">|</span><button class="text-[10px] text-[var(--mt)] font-semibold" style="background:none;border:none;cursor:pointer" onclick="filterAll(\''+escA(c)+'\',false)">Сброс</button></div>'+v.map(function(x){return '<label class="fi"><input type="checkbox" '+(a[x]?'checked':'')+' onchange="toggleF(\''+escA(c)+'\',\''+escA(x)+'\',this.checked)">'+esc(x)+'</label>';}).join('')+'</div></div>';}).join('')+'<input type="search" placeholder="Поиск..." class="flex-1 min-w-[150px]" value="'+esc(S.search)+'" oninput="S.search=this.value;render()">';}
function toggleF(c,v,on){if(!S.filters[c])S.filters[c]={};if(on)S.filters[c][v]=1;else delete S.filters[c][v];if(!Object.keys(S.filters[c]).length)delete S.filters[c];buildFilters();render();}
function filterAll(c,a){if(a)delete S.filters[c];else S.filters[c]={};buildFilters();render();}
function buildGrp(){$('grpBy').innerHTML='<option value="">Нет</option>'+S.headers.map(function(h){return '<option value="'+esc(h)+'" '+(S.groupBy===h?'selected':'')+'>'+esc(h)+'</option>';}).join('');}
function buildColPanel(){if(!$('colPanel'))return;$('colPanel').innerHTML='<div class="flex justify-between mb-2"><span class="text-xs font-bold">Столбцы</span><div class="flex gap-1"><button class="text-[10px] font-bold text-[var(--mt)]" style="background:none;border:none;cursor:pointer" onclick="setAllVis(true)">Все</button><span class="text-[10px] text-[var(--bd)]">|</span><button class="text-[10px] font-bold text-[var(--mt)]" style="background:none;border:none;cursor:pointer" onclick="setAllVis(false)">Нет</button></div></div>'+S.headers.map(function(h){return '<label class="fi"><input type="checkbox" '+(S.visCols[h]?'checked':'')+' onchange="S.visCols[\''+escA(h)+'\']=this.checked;render()"> '+esc(h)+'</label>';}).join('');}
function setAllVis(v){S.headers.forEach(function(h){S.visCols[h]=v;});buildColPanel();render();}
function getFiltered(oA){var d=S.tasks.map(function(t,i){var r={};for(var k in t)r[k]=t[k];r._i=i;return r;});for(var c in S.filters){var k=Object.keys(S.filters[c]);if(!k.length)continue;d=d.filter(function(t){return k.indexOf(String(t[c]||'').trim())>-1;});}if(S.search.trim()){var q=S.search.toLowerCase();d=d.filter(function(t){return S.headers.some(function(h){return String(t[h]||'').toLowerCase().indexOf(q)>-1;});});}if(oA)d=d.filter(function(t){return S.assignments[t._i];});return d;}
function doSort(c){if(S.sortCol===c)S.sortDir*=-1;else{S.sortCol=c;S.sortDir=1;}render();}

function render(){renderStats();var data=getFiltered(),vH=S.headers.filter(function(h){return S.visCols[h];}),hA=S.executors.length>0,grp=S.groupBy;if(S.sortCol){data.sort(function(a,b){var va=String(a[S.sortCol]||''),vb=String(b[S.sortCol]||''),da=parseDate(va),db=parseDate(vb);if(da&&db)return(da-db)*S.sortDir;var na=parseFloat(va.replace(/,/g,'.')),nb=parseFloat(vb.replace(/,/g,'.'));if(!isNaN(na)&&!isNaN(nb))return(na-nb)*S.sortDir;return va.localeCompare(vb,'ru')*S.sortDir;});}var ncol=vH.length+(hA?1:0),cg='';if(hA)cg+='<col style="width:32px">';vH.forEach(function(h){cg+='<col style="width:'+(S.colWidths[h]||'auto')+'">';});$('tCols').innerHTML=cg;var th='<tr>';if(hA)th+='<th style="width:32px;cursor:default"><i class="fa-solid fa-user-check text-[8px]"></i></th>';vH.forEach(function(h){var s=S.sortCol===h,ico=s?(S.sortDir===1?'fa-arrow-up':'fa-arrow-down'):'fa-sort';th+='<th class="'+(s?'sorted':'')+'" onclick="doSort(\''+escA(h)+'\')">'+esc(h)+' <i class="fa-solid '+ico+'" style="font-size:8px;opacity:'+(s?1:.25)+'"></i><div class="rh" onmousedown="startResize(event,\''+escA(h)+'\')"></div></th>';});th+='</tr>';$('tHead').innerHTML=th;var tb='';if(!data.length){tb='<tr><td colspan="'+ncol+'" style="text-align:center;padding:40px;color:var(--mt)"><i class="fa-solid fa-filter-circle-xmark text-2xl mb-2 block opacity-30"></i>Нет данных</td></tr>';}else if(grp){var g={};data.forEach(function(t){var k=String(t[grp]||'').trim()||'(пусто)';if(!g[k])g[k]=[];g[k].push(t);});Object.keys(g).sort(function(a,b){return a.localeCompare(b,'ru');}).forEach(function(gn){tb+='<tr class="gh"><td colspan="'+ncol+'"><i class="fa-solid fa-layer-group mr-2 text-[10px]"></i>'+esc(gn)+' <span class="text-xs text-[var(--mt)] font-normal ml-2">('+g[gn].length+')</span></td></tr>';g[gn].forEach(function(t){tb+=mkRow(t,vH,hA);});});}else{data.forEach(function(t){tb+=mkRow(t,vH,hA);});}$('tBody').innerHTML=tb;$('rowCnt').textContent=data.length+' из '+S.tasks.length;syncScroll();}

function mkRow(t,vH,hA){var h='<tr class="'+rowCls(t['Статус'])+'" ondblclick="toggleWrap(event)">';if(hA){var a=S.assignments[t._i];h+='<td><button class="ab '+(a?'on':'')+'" onclick="event.stopPropagation();openAsgn('+t._i+')" title="'+(a?esc(a):'Назначить')+'"><i class="fa-solid '+(a?'fa-user-check':'fa-user-plus')+'"></i></button></td>';}vH.forEach(function(c){var v=String(t[c]||'');if(c==='Статус'&&v)v='<span class="b '+badgeCls(v)+'">'+esc(v)+'</span>';else if((c==='План'||c==='Факт')&&v){var n=parseFloat(v.replace(/,/g,'.'));if(!isNaN(n)&&n>0){var b='';if(c==='Факт'){var p=parseFloat(String(t['План']||'0').replace(/,/g,'.'));if(p>0){var pc=Math.min(100,n/p*100);b='<div class="pb"><div class="pf" style="width:'+pc+'%;background:'+(pc>=95?'var(--sc)':pc>=50?'var(--wn)':'var(--dn)')+'"></div></div>';}}v='<span class="mono text-xs">'+esc(v)+'</span>'+b;}}else if((c==='Начало'||c==='Окончание')&&v){var d=excelToDate(t[c]);v='<span class="mono text-xs">'+esc(d?fmtD(d):v)+'</span>';}else if(c==='Контр. Срок')v='<span class="mono text-xs">'+esc(v)+'</span>';else v=esc(v);h+='<td>'+v+'</td>';});return h+'</tr>';}
function toggleWrap(e){var td=e.target.closest('td');if(td)td.classList.toggle('wrap');}

var _rC=null,_rX=0,_rW=0;
function startResize(e,c){e.preventDefault();e.stopPropagation();_rC=c;_rX=e.clientX;_rW=e.target.parentElement.offsetWidth;e.target.classList.add('act');document.addEventListener('mousemove',doR);document.addEventListener('mouseup',stopR);}
function doR(e){if(!_rC)return;var w=Math.max(20,_rW+(e.clientX-_rX));S.colWidths[_rC]=w;var cols=$('tCols').children,vH=S.headers.filter(function(h){return S.visCols[h];}),o=S.executors.length>0?1:0;for(var i=0;i<vH.length;i++){if(vH[i]===_rC){cols[i+o].style.width=w+'px';break;}}}
function stopR(){closeDDs();document.querySelectorAll('.rh').forEach(function(e){e.classList.remove('act');});_rC=null;document.removeEventListener('mousemove',doR);document.removeEventListener('mouseup',stopR);syncScroll();}
