function openAsgn(i){S.asgnIdx=i;var t=S.tasks[i];$('asgnInfo').innerHTML='<div class="font-medium text-[var(--fg)] mb-1">'+esc(String(t['Задача исполнителя']||t['Основание']||'').slice(0,150))+'</div><div>Тема: <span class="mono text-[var(--ac)]">'+esc(t['Тема']||'')+'</span> · Сектор: <span class="mono text-[var(--ac)]">'+esc(t['Сектор (группа)']||'')+'</span></div>';var s=[],ss={};S.executors.forEach(function(e){if(e['Сектор']&&!ss[e['Сектор']]){ss[e['Сектор']]=1;s.push(e['Сектор']);}});s.sort();$('asgnSek').innerHTML='<option value="">Все</option>'+s.map(function(x){return '<option value="'+esc(x)+'" '+(x===String(t['Сектор (группа)']||'').trim()?'selected':'')+'>'+esc(x)+'</option>';}).join('');$('asgnQ').value='';renderExecList();openModal('asgnModal');}
function renderExecList(){var q=$('asgnQ').value.toLowerCase(),sf=$('asgnSek').value,l=S.executors.filter(function(e){if(q&&e['ФИО'].toLowerCase().indexOf(q)<0&&(e['Должность']||'').toLowerCase().indexOf(q)<0)return false;if(sf&&e['Сектор']!==sf)return false;return true;});var c=S.assignments[S.asgnIdx],h='';if(c)h+='<div class="ei" onclick="rmAsgn()" style="border-bottom:1px solid var(--bd);margin-bottom:4px;padding-bottom:8px"><i class="fa-solid fa-user-xmark text-[var(--dn)]"></i><span class="text-xs font-semibold text-[var(--dn)]">Снять: '+esc(c)+'</span></div>';if(!l.length)h+='<div class="text-xs text-[var(--mt)] text-center py-4 font-semibold">'+(S.executors.length?'Не найдено':'Не загружены')+'</div>';else h+=l.map(function(e){var ic=e['ФИО']===c;return '<div class="ei" onclick="doAsgn(\''+escA(e['ФИО'])+'\')" style="'+(ic?'background:var(--acg);border:1px solid var(--acd);border-radius:6px':'')+'"><div class="flex-1 min-w-0 truncate"><div class="text-xs font-semibold truncate">'+esc(e['ФИО'])+'</div><div class="esek">Сектор '+esc(e['Сектор']||'?')+'</div><div class="text-[10px] text-[var(--mt)] truncate">'+esc(e['Должность']||'')+'</div>'+(e['Телефон']?'<div class="text-[10px] text-[var(--mt)]"><i class="fa-solid fa-phone text-[8px] mr-1"></i>'+esc(e['Телефон'])+'</div>':'')+(e['Почта']?'<div class="text-[10px] text-[var(--mt)] truncate"><i class="fa-solid fa-envelope text-[8px] mr-1"></i>'+esc(e['Почта'])+'</div>':'')+'</div>'+(ic?'<i class="fa-solid fa-check text-[var(--ac)]"></i>':'')+'</div>';}).join('');$('asgnList').innerHTML=h;}
function doAsgn(f){S.assignments[S.asgnIdx]=f;closeModal('asgnModal');render();toast('Назначен: '+f);}function rmAsgn(){delete S.assignments[S.asgnIdx];closeModal('asgnModal');render();toast('Снято');}

function openIssueList(){var dd=$('issueDD'),c={};for(var k in S.assignments){c[S.assignments[k]]=(c[S.assignments[k]]||0)+1;}var ks=Object.keys(c);if(!ks.length){dd.innerHTML='<div class="p-3 text-xs text-[var(--mt)] font-semibold">Нет назначенных</div>';toggleDD(dd.previousElementSibling,'issueDD');return;}dd.innerHTML=ks.sort(function(a,b){return a.localeCompare(b,'ru');}).map(function(f){var e=S.executors.find(function(x){return x['ФИО']===f;});return '<div class="ei" onclick="closeDDs();genIssue(\''+escA(f)+'\')"><div class="flex-1"><div class="text-xs font-semibold">'+esc(f)+'</div><div class="esek">Сектор '+(e?esc(e['Сектор']):'?')+' · '+c[f]+' задач</div></div></div>';}).join('');toggleDD(dd.previousElementSibling,'issueDD');}
function genIssue(f){var ex=S.executors.find(function(e){return e['ФИО']===f;});var ts=S.tasks.map(function(t,i){var r={};for(var k in t)r[k]=t[k];r._i=i;return r;}).filter(function(t){return S.assignments[t._i]===f;});S.issueData={fio:f,exec:ex,tasks:ts};var inf='<strong>'+esc(f)+'</strong>'+(ex?'<br>Сектор: <span class="mono text-[var(--ac)]">'+esc(ex['Сектор']||'')+'</span><br>'+esc(ex['Должность']||''):'');inf+='<br>Задач: <strong>'+ts.length+'</strong>';$('issueExecInfo').innerHTML=inf;$('issueTitle').textContent='Выдача: '+f;$('issueArea').value=genText(ts,true,true,f);openModal('issueModal');}
function exportIssueXLSX(){if(!S.issueData)return;var ws=XLSX.utils.json_to_sheet(S.issueData.tasks);var wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Выдача");XLSX.writeFile(wb,'Выдача_'+S.issueData.fio.replace(/\s+/g,'_')+'.xlsx');}
function exportIssueMD(){if(!S.issueData)return;dlFile('Выдача.md',$('issueArea').value);}
function exportIssueObs(){if(!S.issueData)return;dlFile('Выдача_Tasks.md',genText(S.issueData.tasks,false,true,S.issueData.fio));}

function genText(d,isMD,isG,k){var vH=S.headers.filter(function(h){return S.visCols[h];});var o='';if(isMD){o+='# Выдача: '+(k||'Выборка')+'\n\n**Дата:** '+new Date().toLocaleDateString('ru-RU')+'\n**Записей:** '+d.length+'\n\n| '+vH.join(' | ')+' |\n|'+vH.map(function(){return '---';}).join('|')+'|\n';d.forEach(function(t){o+='| '+vH.map(function(h){return String(t[h]||'').replace(/\|/g,' ').replace(/\n/g,' ');}).join(' | ')+' |\n';});}else{o+='---\ntags: [выдача]\ndate: '+new Date().toISOString().slice(0,10)+'\n---\n\n# Задачи: '+(k||'Выборка')+'\n\n';if(isG){var g={};d.forEach(function(t){var x=String(t['Тема']||t['Основание']||'Без темы').slice(0,80);if(!g[x])g[x]=[];g[x].push(t);});for(var gn in g){o+='## '+gn+'\n';g[gn].forEach(function(t){var tk=String(t['Задача исполнителя']||t['Основание']||'').replace(/\n/g,' ');o+='- [ ] '+tk+(t['Тема']?' [Тема: '+t['Тема']+']':'')+(toYMD(t['Контр. Срок'])?' 📅 '+toYMD(t['Контр. Срок']):'')+'\n';});o+='\n';}}else d.forEach(function(t){o+='- [ ] '+String(t['Задача исполнителя']||t['Основание']||'').replace(/\n/g,' ')+(toYMD(t['Контр. Срок'])?' 📅 '+toYMD(t['Контр. Срок']):'')+'\n';});}return o;}

function openExportModal(){genExpTxt();openModal('expModal');}
function genExpTxt(){var oA=$('expAsgn').checked,g=$('expGrp').checked,d=getFiltered(oA);$('expArea').value=genText(d,true,g,oA?'Назначенные':'Выборка');}
function doExpXLSX(){var d=getFiltered($('expAsgn').checked),vH=S.headers.filter(function(h){return S.visCols[h];});var ex=d.map(function(t){var r={};vH.forEach(function(h){r[h]=t[h];});if(S.executors.length)r['Назначен']=S.assignments[t._i]||'';return r;});var ws=XLSX.utils.json_to_sheet(ex);var wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Выборка");XLSX.writeFile(wb,'Выборка.xlsx');}
function doExpMD(){dlFile('Выборка.md',$('expArea').value);}
function doExpObs(){var oA=$('expAsgn').checked,g=$('expGrp').checked;dlFile('Выборка_Tasks.md',genText(getFiltered(oA),false,g,oA?'Назначенные':'Выборка'));}

function openSaveModal(){$('saveName').value='';openModal('saveModal');}
function doSave(){var n=$('saveName').value.trim();if(!n){toast('Введите название');return;}var st={name:n,filters:S.filters,search:S.search,groupBy:S.groupBy,sortCol:S.sortCol,sortDir:S.sortDir,visCols:{},assignments:{},colWidths:{}};S.headers.forEach(function(h){if(S.visCols[h])st.visCols[h]=1;});for(var k in S.assignments)st.assignments[k]=S.assignments[k];for(var k in S.colWidths)st.colWidths[k]=S.colWidths[k];var idx=-1;for(var i=0;i<S.saved.length;i++){if(S.saved[i].name===n){idx=i;break;}}if(idx>-1)S.saved[idx]=st;else S.saved.push(st);safeLS('pm_sv',S.saved);closeModal('saveModal');renderSaved();toast('Сохранено: '+n);}
function loadSaved(i){var sv=S.saved[i];if(!sv)return;S.filters=sv.filters||{};S.search=sv.search||'';S.groupBy=sv.groupBy||'';S.sortCol=sv.sortCol||'';S.sortDir=sv.sortDir||1;S.headers.forEach(function(h){S.visCols[h]=!!sv.visCols[h];});S.assignments=sv.assignments||{};S.colWidths=sv.colWidths||{};buildGrp();buildFilters();buildColPanel();render();toast('Загружено: '+sv.name);}
function rmSaved(i){S.saved.splice(i,1);safeLS('pm_sv',S.saved);renderSaved();toast('Удалено');}
function renderSaved(){if(!S.saved.length){$('savedBar').classList.add('hidden');return;}$('savedBar').classList.remove('hidden');$('savedTags').innerHTML=S.saved.map(function(s,i){return '<span class="stg" onclick="loadSaved('+i+')">'+esc(s.name)+' <span class="x" onclick="event.stopPropagation();rmSaved('+i+')"><i class="fa-solid fa-xmark"></i></span></span>';}).join('');}
function resetAll(){S.filters={};S.search='';S.groupBy='';S.sortCol='';S.sortDir=1;S.assignments={};S.colWidths={};S.headers.forEach(function(h){S.visCols[h]=true;});buildGrp();buildFilters();buildColPanel();render();toast('Сброшено');}
